# This is a basic workflow to help you get started with Actions

name: Create PR for new release

on: 
  workflow_dispatch:
    inputs:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  branching:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    container:
      image: node:18

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: npm install
        run: |
          npm ci

      # Runs a single command using the runners shell
      - name: generate version number and changelog file
        run: |
          git config --global --add safe.directory /__w/release-code/release-code
          git config --global user.email "flavia.taho@grupoboticario.com.br"
          git config --global user.name "Célula de Ativação"

          echo "creating commit for package.json..."
          VERSION=$(npm run release:version | tail -n 1)
          echo "version=$VERSION" >> $GITHUB_ENV

          npm run release:changelog | tail -n +5 > .last_changelog
          cat .last_changelog > .changelog
          echo $(cat .last_changelog)

          cat CHANGELOG.md >> .changelog
          cat .changelog > CHANGELOG.md


      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ env.version }}
      #     name: Release ${{ env.version }}
      #     bodyFile: .changelog

      - name: update package.json version 
        run: |
          node -e "const package = require('./package.json'); package.version = '${{ env.version }}'; require('fs').writeFileSync('package.json', JSON.stringify(package, null, 2))"
          git add package.json
          git add CHANGELOG.md
          git commit -m "chore: Bump version ${{ env.version }}"

      - name: create version pull request to main
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Bump version to release [${{ env.version }}]"
          body: "Pull request created automatically for versioning"
          branch: bump/${{ env.version }}
          base: main
          add-paths: |
            package.json
            CHANGELOG.md

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: 'bump/${{ env.version }}',
              base: 'release',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });

      # - name: create version pull request to release
      #   uses: poorva17/create-pr-action@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     HEAD_BRANCH: bump/${{ env.version }} 
      #     BASE_BRANCH: release

      # - name: create version pull request to release
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     title: "Bump version to release [${{ env.version }}]"
      #     body: "Pull request created automatically for versioning"
      #     branch: bump/${{ env.version }}
      #     base: release
      #     add-paths: |
      #       package.json
      #       CHANGELOG.md
