# This is a basic workflow to help you get started with Actions

name: Create new release branch

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  branching:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    container:
      image: node:18

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        # with:
        #   fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: npm install
        run: |
          npm ci

      # Runs a single command using the runners shell
      - name: create version file
        run: |
          echo $(git --version)
          git config --global --add safe.directory /__w/release-code/release-code
          git config --global user.email "flavia.taho@grupoboticario.com.br"
          git config --global user.name "Célula de Ativação"

          npm run release:version | tail -n 1 > .version
          echo "deploying new version [$(cat .version)]"

          NEW_CONF_VERSION="release_branch=release/$(cat .version)"
          echo $NEW_CONF_VERSION >> $GITHUB_ENV

      - name: create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.release_branch }}
          sha: '${{ github.event.pull_request.head.sha }}'
