name: Create pull requests to release and main branches

on:
  workflow_dispatch:
    inputs:

permissions:
  contents: write

jobs:
  branching:
    runs-on: ubuntu-latest
    container:
      image: node:18

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: npm install
        run: |
          npm ci

      - name: generate version number and changelog file
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "creating commit for package.json..."
          VERSION=$(npm run release:version | tail -n 1)
          echo "version=$VERSION" >> $GITHUB_ENV

          npm run release:changelog | tail -n +5 > .last_changelog

          cat .last_changelog > .changelog
          echo $(cat .last_changelog)

          cat CHANGELOG.md >> .changelog
          cat .changelog > CHANGELOG.md

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.version }}
          name: Release ${{ env.version }}
          bodyFile: .last_changelog

      - name: update package.json version
        run: |
          node -e "const package = require('./package.json'); package.version = '${{ env.version }}'; require('fs').writeFileSync('package.json', JSON.stringify(package, null, 2))"
          git add package.json
          git add CHANGELOG.md
          git commit -m "chore: Bump version ${{ env.version }}"
          git push

      - name: create release pull request to release branch
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Bump version to release [${{ env.version }}]',
              owner,
              repo,
              head: 'release',
              base: 'main',
              body: [
                'Pull request created automatically for versioning',
              ].join('\n')
            });
