# This is a basic workflow to help you get started with Actions

name: Deploy new version

on:
  push:
    branches: [ "" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: npm install
        run: |
          npm ci

      # Runs a single command using the runners shell
      - name: create version file
        run: |
          npm run release -c .release-it.json --ci --release-version > .version

      # # Runs a single command using the runners shell
      # - name: Run release it
      #   run: |
      #     npm run release -c .release-it.json --ci
