on: 
  workflow_run:
    workflows: ["Create pull requests to release and main branches"]
    types:
      - completed
  push:
    branches:
      - main
      - releases
    paths-ignore:
      - '**/*.md'
      - '.scafflater/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - releases
    paths-ignore:
      - "**/*.md"
  create:

name: Standard

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'create' && contains(github.ref, 'refs/heads/releases/')) || github.event_name != 'create'  }}
    steps:
      - uses: actions/checkout@v3
      - name: "Test and build"
        run: echo "all checks for build and test done!"

  ci_docker:
    name: CI - Docker
    if: ${{ success() && github.actor != 'dependabot[bot]' }}
    needs: [ci]
    runs-on: ubuntu-latest 
    steps:
      - name: Docker Build and Push
        run: echo "Push to EKS"
  cd_dev:
    name: CD - DEV
    if: ${{ success() && github.base_ref == 'main' }}
    needs: [ci_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Infra
        run: echo "Deploying infra"
      - name: Deploy App
        run: echo "Deploying App"
  cd_hml:
    name: CD - HML
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    needs: [ci_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Infra
        run: echo "Deploying infra"
      - name: Deploy App
        run: echo "Deploying App"
  cd_prd:
    name: CD - PRD
    if: ${{ success() && contains(github.ref, 'refs/heads/releases/') }}
    needs: [ci_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Infra
        run: echo "Deploying infra"
      - name: Deploy App
        run: echo "Deploying App"
